### ISSUE TITLE
passport-remember-me is not working with passport 0.5.2

### ISSUE THREAD

**Issue by gritschf** [jaredhanson/passport-remember-me#33]
Hi.
I've updated to passport 0.5.2. 
With this version `passport-remember-me` isn't working anymore.  

```
TypeError: Cannot set properties of undefined (setting 'user')
    at [mydir]\node_modules\passport-remember-me\node_modules\passport\lib\passport\http\request.js:45:35
    at pass ([mydir]\node_modules\passport\lib\authenticator.js:274:43)
    at serialized ([mydir]\node_modules\passport\lib\authenticator.js:283:7)
    at UserSerializer.serializeUser ([mydir]\dist\auth\user.serializer.js:23:9)
    at [mydir]\node_modules\@nestjs\passport\dist\passport\passport.serializer.js:8:61
    at pass ([mydir]\node_modules\passport\lib\authenticator.js:291:9)
    at Authenticator.serializeUser ([mydir]\node_modules\passport\lib\authenticator.js:296:5)
    at IncomingMessage.req.login.req.logIn ([mydir]\node_modules\passport-remember-me\node_modules\passport\lib\passport\http\request.js:43:29)
    at [mydir]\node_modules\@nestjs\passport\dist\auth.guard.js:63:64
    at new Promise (<anonymous>)
```

I think it is because the dependency of this package is `~0.1.1`

```
  "dependencies": {
    "pkginfo": "0.2.x",
    "passport": "~0.1.1"
  },
```

When i replace the passport dependency manually with the content of version `0.5.2` its working again:

![grafik](https://user-images.githubusercontent.com/10422951/153865033-7312a013-7757-4844-8ffe-22304aa866ac.png)

**Comment by davidzwa** [comment]
Can confirm here that I ran into exactly the same issue.

**Comment by gritschf** [comment]
@jaredhanson could you please take a look at this and release a new version? (same problem with version `0.5.3`)

**Comment by bazineta** [comment]
@gritschf @davidzwa Take a look at #10. Yes, it's from 2015; yes, it still fixes the problem. No, I don't know why it's never been merged.

**Comment by atog** [comment]
Can confirm it is still a problem with passport 0.6.0 and yes https://github.com/jaredhanson/passport-remember-me/pull/10 still fixes the problem.

**Comment by aikimcr** [comment]
It looks very much like this is just not being maintained anymore.  Rather than patch or fork, I'm just going to abandon this strategy.
