### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by exagyde** [jaredhanson/passport-remember-me#34]
Hi guys,
I'm trying to implement a remember-me strategy for my NodeJS application with Passport, I have tried the main example available on the official Passport website (https://www.passportjs.org/packages/passport-remember-me/) but that doesn't work, I have an error from the package and I don't now how to fix that : 

```
TypeError: Cannot read properties of undefined (reading 'remember_me')
    at Strategy.authenticate (/Users/.../node_modules/passport-remember-me/lib/strategy.js:51:26)
    at attempt (/Users/.../node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/Users/.../node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/Users/.../node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/.../node_modules/express/lib/router/index.js:328:13)
    at /Users/.../node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/.../node_modules/express/lib/router/index.js:346:12)
    at next (/Users/.../node_modules/express/lib/router/index.js:280:10)
    at strategy.pass (/Users/.../node_modules/passport/lib/middleware/authenticate.js:346:9)
    at SessionStrategy.authenticate (/Users/.../node_modules/passport/lib/strategies/session.js:75:10)
```

Do you have any solution or alternative for that ?

**Comment by chustert** [comment]
Apparently cookie-parser has to be installed as it doesnt come with express anymore. 
[npm ](https://www.npmjs.com/package/cookie-parser)
It loads the site correctly, however, now I have the problem that the login keeps loading...

**Comment by Coinhexa** [comment]
Without cookie-parser it gives me this error and with cookie parser it gives me the error on #33  what am I supposed to do?
